Декоративные элементы на внутренней странице
htmlacademy-htmlcss/1775757-technomart-31 pull request #12
Opened 2021-06-17 16:48 UTC by Lobanov88

2021-06-21 09:02 UTC, Lobanov88 commented
Декоративные элементы на внутренней странице

2021-06-21 18:50 UTC, Lobanov88 commented
Декоративные элементы внутренней страницы

2021-06-22 08:07 UTC, CCher requested changes
По Пиксель-перфект есть расхождения:
![image](https://user-images.githubusercontent.com/12691832/122886166-5f9a8400-d348-11eb-8ac0-39665b665c30.png)

цена на красных кнопках должна быть чуть ниже

![image](https://user-images.githubusercontent.com/12691832/122886916-0c750100-d349-11eb-9052-5356eaaae5f4.png)

И попробуйте блоки и элементы выровнять паддингами и марджинами. Вот для примера сделал: 
![image](https://user-images.githubusercontent.com/12691832/122887715-d71ce300-d349-11eb-881c-c9af615dd6d6.png)

2021-06-22 09:23 UTC, Lobanov88 commented
new

2021-06-22 10:26 UTC, CCher approved these changes

2021-06-22 10:26 UTC, merged