Разметка страниц, создание страниц и папок, добавление изображений
htmlacademy-htmlcss/1775757-technomart-31 pull request #2
Opened 2021-05-21 23:19 UTC by Lobanov88

Созданы папки css, js и img, файлы blank.html и catalog.html. Проведена разметка страниц index.html, blank.html и catalog.html. Добавлены изображения.

2021-05-22 07:58 UTC, CCher requested changes
В целом качественная разметка и даже больше, чем требовалось по ДЗ.
Но есть несколько недочётов.
1. Критерий Б5 - Не проходит валидацию (скриншот ниже)
![image](https://user-images.githubusercontent.com/12691832/119218783-d7c41e80-baea-11eb-98de-0f17f376f0f5.png)
2. Критерий Б14 - Отсутствуют заглавные буквы в именах файлов

2021-05-22 07:58 UTC, CCher commented on index.html
> +            КредитЗалезть в долговую яму стало проще!<br>
Здесь опечатка кредитзалезть

2021-05-22 07:58 UTC, CCher commented on index.html
> +      </section>
в section лучше вкладывать article. Секшены вроде как равноправные

2021-05-22 19:46 UTC, Lobanov88 commented on index.html
> +            КредитЗалезть в долговую яму стало проще!<br>
Пока исправления не комитил. Смотрю, разбираюсь.

Б5 - может, неверно скопировались строки в валидатор? Смотрю, но не вижу, где doctype пропущен. Там первая строка  в пулреквесте кстати "свернута" была. Может, из-з этого

Б14 - понял, заглавные убираю в названиях файлов

Опечатку понял, убрал

2021-05-22 20:08 UTC, Lobanov88 commented on index.html
> +      </section>
Ну вот вроде бы ведь совсем не article, нет? "предназначенную для независимого распространения или повторного использования" — вот независимо не будет же вроде работать.

section в section проверял на https://caninclude.glitch.me/
Там разрешают, но если не очень, то могу поменять

Может на div ы?

2021-05-23 08:44 UTC, CCher commented on index.html
> +            КредитЗалезть в долговую яму стало проще!<br>
Да, странно. Сейчас во всех трёх файлах Доктайп на месте. Ок.

2021-05-23 08:47 UTC, CCher commented on index.html
> +      </section>
Оставьте как есть. Далее по курсу разметка будет меняться и правильный вариант в конце-концов получится. В ХТМЛ5 очень много свободы и вариативности, так что часто не бывает единственно верного решения. Всё нормально.
Присылайте работу на проверку - зачтено.

2021-05-23 16:27 UTC, Lobanov88 commented on index.html
> +      </section>
Закомитил и запушил изменения. Они отобразились новым комитом. Как понимаю все, или что-то еще нужно сделать?

2021-05-23 20:28 UTC, CCher approved these changes

2021-05-23 20:28 UTC, merged